platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine

params:
  java_src: java-dockerfile-source
  node_src: node-dockerfile-source
  target: java-node-dockerfile-build
  java_tag: 8-jdk
  node_tag: 8.1
  dockerfile_path: alpine/Dockerfile

inputs:
- name: java-node-dockerfile-ci-source
- name: java-dockerfile-source
- name: node-dockerfile-source
outputs: 
- name: java-node-dockerfile-build
run:
  path: java-node-dockerfile-ci-source/src/main/ci/build.sh
