jobs:
- name: compose-dockerfile
  public: true
  serial: true
  plan:
  - aggregate:
    - get: java-node-dockerfile-ci-source
      trigger: true
    - get: java-dockerfile-source
      trigger: true
    - get: node-dockerfile-source
      trigger: true
    - get: java-node-dockerfile-source
  - task: compose
    file: java-node-dockerfile-ci-source/src/main/ci/build.yaml
  - task: commit
    file: java-node-dockerfile-ci-source/src/main/ci/commit.yaml
  - put: java-node-dockerfile-source
    params:
      repository: updated-java-node-dockerfile-source

resources:
- name: java-node-dockerfile-source
  type: git
  source:
    uri: git@github.com:timotto/java-node-dockerfile.git
    branch: master
    private_key: {{git-ssh-key}}

- name: java-node-dockerfile-ci-source
  type: git
  source:
    uri: https://github.com/timotto/java-node-dockerfile-ci
    branch: master

- name: java-dockerfile-source
  type: git
  source:
    uri: https://github.com/docker-library/openjdk.git
    branch: master

- name: node-dockerfile-source
  type: git
  source:
    uri: https://github.com/nodejs/docker-node.git
    branch: master
